"""An offline ``LLMClient`` for demos and local dev — no API key, no network.

``LLM_PROVIDER=stub`` selects this. It does a crude regex pass over the
rendered raw extractions (amounts, a bank reference, an invoice-ish token,
a labeled payer name) and emits ONE ``PaymentDraft`` with confidence
reflecting how much it could parse — everything it produces is meant to be
corrected by a human where confidence is low or a checkpoint fails.
"""

from __future__ import annotations

import re
from decimal import Decimal, InvalidOperation
from typing import TypeVar

from pydantic import BaseModel

T = TypeVar("T", bound=BaseModel)

_NOTE = (
    "Generated by the stub LLM (LLM_PROVIDER=stub) — no model was called. "
    "Treat every field as a guess and review it."
)
_PAYER_UNKNOWN = ""  # the stub cannot identify the payer; leave it for the reviewer to fill in

# grouped (1,23,456.78 / 12,345) or a decimal amount (1234.56) — the confident tier
_AMOUNT_RE = re.compile(r"(?<![\d.,])\d{1,3}(?:,\d{2,3})+(?:\.\d{1,2})?|(?<![\d.,])\d+\.\d{1,2}\b")
# a plain 4-9 digit integer (500000) — used only when the confident tier is empty
_PLAIN_INT_RE = re.compile(r"(?<![\d.,])\d{4,9}(?![\d.,])")
# a bank reference: the keyword, then an alnum token that contains at least one digit
_REF_KEYWORD_RE = re.compile(
    r"\b(UTR|RTGS|NEFT|IMPS)\b[\s:#/-]*((?=[A-Za-z0-9]*\d)[A-Za-z0-9]{6,22})", re.I
)
_REF_BARE_RE = re.compile(r"\b(?=[A-Z0-9]*\d)[A-Z]{4}[A-Z0-9]{7,}\b")
# INV / BILL immediately followed by a separator or digit, then an id token
# that itself contains a digit — so the plain words "invoice" / "invoices" and
# "Invoice Date" don't match.
_INVOICE_RE = re.compile(
    r"\b(?:INV|BILL)(?=[\s:#/.-]|\d)[\s:#/.-]*((?=[A-Za-z0-9/-]*\d)[A-Za-z0-9][A-Za-z0-9/-]{1,})",
    re.I,
)
# fallback: an "invoice no" / "inv number" / "bill no" LABEL (not attached
# to an id, e.g. a table header cell: "Invoice Number" / "Bill No"), then
# the first code-shaped token (letters immediately followed by >=6 digits,
# the usual vendor invoice-id shape: "ACM2510006275") within a short
# window after it.
_INVOICE_LABEL_RE = re.compile(r"\b(?:invoice|inv|bill)\s*(?:no\.?|number|#)", re.I)
_CODE_RE = re.compile(r"\b[A-Za-z]{2,6}\d{6,}\b")
_LABEL_WINDOW = 200
# a labeled payer-ish name: "Beneficiary's name:", "Beneficiary Name:",
# "Remitter's name:", "Vendor Name:", "Payer Name:" followed by a name on
# the same line (up to the next newline or table-cell separator).
_PAYER_LABEL_RE = re.compile(
    r"(?:beneficiary|vendor|remitter|payer)'?s?\s*name\s*[:#]\s*([^\n|]{2,80})",
    re.I,
)


def _amounts(text: str) -> list[Decimal]:
    def _parse(raws: list[str]) -> list[Decimal]:
        out: list[Decimal] = []
        for raw in raws:
            try:
                value = Decimal(raw.replace(",", ""))
            except InvalidOperation:
                continue
            if value >= 1:
                out.append(value)
        return out

    found = _parse(_AMOUNT_RE.findall(text))
    if not found:
        # no comma-grouped or decimal amount anywhere — fall back to plain
        # integers, ignoring anything year-sized to skip stray dates.
        found = [v for v in _parse(_PLAIN_INT_RE.findall(text)) if not 1900 <= v <= 2100]
    return sorted(set(found), reverse=True)


def _reference(text: str) -> tuple[str | None, str | None]:
    m = _REF_KEYWORD_RE.search(text)
    if m:
        return m.group(2), m.group(1).lower()
    m2 = _REF_BARE_RE.search(text)
    if m2:
        return m2.group(0), "utr"
    return None, None


def _invoice_number(text: str) -> str:
    m = _INVOICE_RE.search(text)
    if m:
        return m.group(1)
    label = _INVOICE_LABEL_RE.search(text)
    if label:
        window = text[label.end() : label.end() + _LABEL_WINDOW]
        code = _CODE_RE.search(window)
        if code:
            return code.group(0)
    return ""


def _payer_name(text: str) -> str:
    m = _PAYER_LABEL_RE.search(text)
    return m.group(1).strip() if m else _PAYER_UNKNOWN


def _draft(text: str) -> dict[str, object]:
    amounts = _amounts(text)
    top = amounts[0] if amounts else Decimal("0")
    reference, reference_type = _reference(text)
    invoice_number = _invoice_number(text)
    confidence = 0.2
    if top > 0:
        confidence += 0.35
    if reference:
        confidence += 0.2
    if invoice_number:
        confidence += 0.2
    confidence = min(confidence, 0.95)
    return {
        "payer_name": _payer_name(text),
        "payment_reference": reference,
        "payment_reference_type": reference_type,
        "currency": "INR",
        "total_paid_amount": top,
        "line_items": [
            {
                "invoice_number": invoice_number,
                "invoice_amount": top,
                "amount_paid": top,
            }
        ],
        "confidence": round(confidence, 2),
    }


class StubLLMClient:
    """Deterministic, offline. ``parse`` ignores ``system`` and best-effort
    parses ``user`` (the rendered raw extractions)."""

    def parse(self, *, system: str, user: str, output_model: type[T]) -> T:
        data = {"is_remittance": True, "notes": _NOTE, "payments": [_draft(user)]}
        return output_model.model_validate(data)
