"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-09-09 18:15:25.745253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('internet_message_id', sa.String(length=998), nullable=False),
    sa.Column('sender_address', sa.String(length=320), nullable=False),
    sa.Column('sender_domain', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('raw_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('new', 'classified', 'extracted', 'normalized', 'review', 'done', 'error')", name='ck_email_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internet_message_id', name='uq_email_internet_message_id')
    )
    op.create_index(op.f('ix_email_status'), 'email', ['status'], unique=False)
    op.create_table('poll_state',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('delta_token', sa.Text(), nullable=True),
    sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('id = 1', name='poll_state_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sender_domains', sa.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('format_hint', sa.Text(), nullable=True),
    sa.Column('column_hints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('blob_url', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_email_id'), 'attachment', ['email_id'], unique=False)
    op.create_table('extraction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('canonical', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_remittance', sa.Boolean(), nullable=False),
    sa.Column('validation_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('raw_llm_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=320), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending_review', 'approved', 'rejected')", name='ck_extraction_status'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_extraction_confidence'),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_email_id'), 'extraction', ['email_id'], unique=False)
    op.create_table('extraction_source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('ref', sa.Text(), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("kind IN ('body_table', 'excel', 'pdf_text', 'pdf_scanned', 'image')", name='ck_extraction_source_kind'),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_source_email_id'), 'extraction_source', ['email_id'], unique=False)
    op.create_table('delivery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extraction_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'delivered', 'failed')", name='ck_delivery_status'),
    sa.ForeignKeyConstraint(['extraction_id'], ['extraction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_extraction_id'), 'delivery', ['extraction_id'], unique=False)
    op.create_index('ix_delivery_status_next_attempt', 'delivery', ['status', 'next_attempt_at'], unique=False)
    op.create_table('extraction_edit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extraction_id', sa.UUID(), nullable=False),
    sa.Column('field_path', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('edited_by', sa.String(length=320), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extraction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_edit_extraction_id'), 'extraction_edit', ['extraction_id'], unique=False)
    op.create_table('raw_extraction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extraction_source_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extractor_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['extraction_source_id'], ['extraction_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_extraction_extraction_source_id'), 'raw_extraction', ['extraction_source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_extraction_extraction_source_id'), table_name='raw_extraction')
    op.drop_table('raw_extraction')
    op.drop_index(op.f('ix_extraction_edit_extraction_id'), table_name='extraction_edit')
    op.drop_table('extraction_edit')
    op.drop_index('ix_delivery_status_next_attempt', table_name='delivery')
    op.drop_index(op.f('ix_delivery_extraction_id'), table_name='delivery')
    op.drop_table('delivery')
    op.drop_index(op.f('ix_extraction_source_email_id'), table_name='extraction_source')
    op.drop_table('extraction_source')
    op.drop_index(op.f('ix_extraction_email_id'), table_name='extraction')
    op.drop_table('extraction')
    op.drop_index(op.f('ix_attachment_email_id'), table_name='attachment')
    op.drop_table('attachment')
    op.drop_table('vendor')
    op.drop_table('poll_state')
    op.drop_index(op.f('ix_email_status'), table_name='email')
    op.drop_table('email')
    # ### end Alembic commands ###
